Feature/suggest ens domain
snapshot-labs/snapshot pull request #1029
Opened 2021-11-10 08:31 UTC by sarmatdev

Fixes #954.

Changes proposed in this pull request:
- Setup graphQL for ENS
- Show user ENS names as suggestions
-

2021-11-10 08:34 UTC, sarmatdev commented
There is my draft PR

How do I need to handle the loading status of fetching names?
What message do I need to show the user if he doesn't have any ENS names, and how it should look?

2021-11-12 01:53 UTC, mktcode commented
I would require wallet connection at the beginning. Then you can look for ENS domains and display them to chose from, plus a "Register Domain" button that just links to the ENS website and later we implement registration through snapshot interface. Text input is not needed at all I think.

2021-11-14 16:17 UTC, sarmatdev commented
@bonustrack What would you say?

2021-11-25 21:08 UTC, sarmatdev commented
Added some improvements

2021-11-26 13:07 UTC, ChaituVR commented
@sarmatdev resolve conflicts plz

2021-11-29 08:24 UTC, ChaituVR requested changes
Doesn't seem to be working, always shows me:
```
It looks like your address does not own any ENS name
```

and also revert changes from yarn.lock

2021-11-29 16:39 UTC, mktcode commented
![image](https://user-images.githubusercontent.com/6792578/143907375-66831aea-81e4-448f-8e02-2c8bfccf8277.png)

2021-11-29 17:01 UTC, mktcode commented on src/composables/useEns.ts
> +        id: web3.value.account
```suggestion
        id: web3.value.account.toLowerCase()
```

2021-11-29 17:08 UTC, mktcode commented on src/views/Setup.vue
> +import { useEns } from '@/composables/useEns';
```suggestion
import { ref, computed, watch } from 'vue';
import { useRouter } from 'vue-router';
import { useEns } from '@/composables/useEns';
import { useWeb3 } from '@/composables/useWeb3';

const { web3 } = useWeb3();
const web3Account = computed(() => web3.value.account);
```

2021-11-29 17:13 UTC, mktcode requested changes
With the changes I suggest it works for me.

I used this pattern, which I see in a lot of components.
```
const { web3 } = useWeb3();
const web3Account = computed(() => web3.value.account);
watch(web3Account, ...);
```

But `web3Account` can actually be moved to `useWeb3`, so that this becomes:
```
const { web3Account } = useWeb3();
watch(web3Account, ...);
```

Can be changed in a successive pull request.

2021-12-06 19:34 UTC, mktcode commented on src/views/Setup.vue
> +loadEns();
Why is this marked as resolved?

2021-12-06 19:43 UTC, mktcode approved these changes

2021-12-06 19:49 UTC, mktcode commented on src/views/Setup.vue
> +watch(web3Account, loadEns);
```suggestion
loadEns();
watch(web3Account, loadEns);
```

To make sure ENS names are loaded when entering the setup page and not ONLY when web3Account changes.

2021-12-06 19:54 UTC, mktcode commented
Committed my changes. This is ready to be merged I'd say.

2021-12-07 11:28 UTC, bonustrack commented
Cool, here is some suggestion
- Dont load suggestion if user is not logged
- Use a small circle loading and not this fat loading placeholder
![image](https://user-images.githubusercontent.com/16245250/145014402-73495d53-250f-4bfa-81ed-5e270c8ef23c.png)
- Don't show "Looks like you dont have ENS domains", now i can see it even if request to query ENS domain is not resolved yet, I think we can just remove it

Maybe a better way to imagine this would be like this:

- If user is not logged, just show a "Connect wallet" button like this:
![image](https://user-images.githubusercontent.com/16245250/145020955-6002fdab-49da-4198-ab2d-48fff2e4e41e.png)

- If user is logged but don't have any domain, show a page to register a space like this:
![image](https://user-images.githubusercontent.com/16245250/145021103-367ae798-851e-4c10-a6e3-81fbb6a67019.png)
The next button would redirect to ENS website

- If user is logged and have domain show the domains as buttons and before the form like this:

![image](https://user-images.githubusercontent.com/16245250/145021208-336142bd-c269-486c-8a3c-f816beb1260a.png)

2021-12-13 13:46 UTC, mktcode commented
@sarmatdev I'll take over from here, if that's ok for you. :)

2021-12-13 15:06 UTC, sarmatdev commented
> @sarmatdev I'll take over from here, if that's ok for you. :)

Yes, do it if you are want

2021-12-16 16:57 UTC, mktcode commented
Closing in favor of: ...

2021-12-16 16:57 UTC, closed without merging