Remove explore endpoint and refactor
snapshot-labs/snapshot pull request #3865
Opened 2023-05-04 10:55 UTC by samuveth

### Issues

#3863 
#1437 

### Changes 

1. TDB

### How to test

1. TDB

### To-Do

- [ ] TDB

### Self-review checklist
- [ ] I have performed a full self-review of my changes
- [ ] I have tested my changes on a preview deployment
- [ ] I have tested my changes on a custom domain
- [ ] I have run end-to-end tests `yarn cypress:test:e2e`, and they have passed

### Additional notes or considerations

2023-05-11 13:41 UTC, Todmy requested changes

2023-05-11 15:29 UTC, Todmy commented
I have noticed that while going back from any space page, a user will be retrieved to the home page with the initial state where we have only 12 items loaded. On one side It's not convenient if I scrolled a couple of times to get to some spaces and on going back I need to scroll again. But from another point of view, if we decide to save the scrolling state: if I have scrolled till the end of the home page, on going back we need to load all available spaces.
Have you thought about this behavior?

2023-05-11 16:57 UTC, j0hnfl0w commented
> I have noticed that while going back from any space page, a user will be retrieved to the home page with the initial state where we have only 12 items loaded. On one side It's not convenient if I scrolled a couple of times to get to some spaces and on going back I need to scroll again. But from another point of view, if we decide to save the scrolling state: if I have scrolled till the end of the home page, on going back we need to load all available spaces. Have you thought about this behavior?

We can do it with <keep-alive /> but i think we can do it later.
Its like a tweeter feed, when after closing an app you return to the same tweet (sometimes it is not work properly)
wdyt @samuveth ?

2023-05-12 02:17 UTC, samuveth commented on src/helpers/apollo.ts
> +  uri: `https://sea-turtle-app-hdjod.ondigitalocean.app/graphql`
Yep, will change it once changes on the HUB were merged.

2023-05-12 02:20 UTC, samuveth commented on src/composables/useSpaces.ts
> +  async function loadSpacesHome(variables: any = {}) {
Not convinced, I think having them separated makes the code easier to read.

2023-05-12 02:39 UTC, samuveth commented
Yes, we can do that by moving the state outside of the composable. Using keep alive will not work because going to a space involved changing the route.

2023-05-15 05:50 UTC, samuveth commented
Changes since last review:
1. Remove use of lists verified.json, flagged proposal urls & ids, and use `verified` & `flagged` from query instead
2. Use `KeepAlive` instead of global state (which was causing issues). @j0hnfl0w I didn't know it was possible to use `KeepAlive` with `RouterView` like [this](https://github.com/snapshot-labs/snapshot/blob/8cd9bfb561b434e2ba41703d87dc03e8de069dd7/src/App.vue#L44).
3. Refactor `BaseSearch`, remove handling of route query to keep the component simple

2023-05-15 15:16 UTC, Todmy approved these changes
tACK

2023-05-16 14:43 UTC, ChaituVR commented on src/helpers/apollo.ts
> +  uri: `https://sea-turtle-app-hdjod.ondigitalocean.app/graphql`
```suggestion
  uri: `${import.meta.env.VITE_HUB_URL}/graphql`
```

2023-05-17 05:37 UTC, merged