feat(login): WalletConnect v2 migration
snapshot-labs/snapshot pull request #3963
Opened 2023-06-05 12:06 UTC by Todmy

### Issues
#3385 

### Changes 
*This PR is only for testing migration, which was done in `lock` library*

### How to test
1. Open the page
2. Login with Wallet Connect
3. Switch wallets
4. Try to perform an action (Vote, Proposal creation, etc)
5. Log out with Wallet Connect

### To-Do
- [ ] 

### Self-review checklist
- [ ] I have performed a full self-review of my changes
- [ ] I have tested my changes on a preview deployment
- [ ] I have tested my changes on different screen sizes (sm, md)
- [ ] I have tested my changes on a custom domain
- [ ] I have run end-to-end tests `yarn cypress:test:e2e`, and they have passed

2023-06-15 04:33 UTC, samuveth commented
Have you tried connecting with any wallet using the QR code. For me MetaMask and Zerion didn't work. Maybe we need to wait until the 28th.

Can you resolve the conflicts?

2023-06-23 03:03 UTC, Xbjb8rVZ7ZJquS96Y4AJtNE4Pe9eNY1QGv requested changes

2023-06-23 03:03 UTC, Xbjb8rVZ7ZJquS96Y4AJtNE4Pe9eNY1QGv commented on src/helpers/connectors.json
src/helpers/connectors.json

2023-06-23 03:03 UTC, Xbjb8rVZ7ZJquS96Y4AJtNE4Pe9eNY1QGv commented on package.json
package.json

2023-06-28 12:33 UTC, ChaituVR approved these changes
tAck

2023-06-28 13:16 UTC, aurelianoB commented
Tried connecting to MM mobile with QR code without succcess

2023-06-28 14:09 UTC, merged