Remove primercss
snapshot-labs/snapshot pull request #599
Opened 2021-09-03 14:10 UTC by samuveth

[] finish replacing all primer classes
[] replace primer tooltip with our own
[] replace primer anim-pulse and anim-scale-in

2021-09-04 13:31 UTC, samuveth commented
![](https://github.trello.services/images/mini-trello-icon.png) [Add sidebar left and tailwindcss](https://trello.com/c/s6COWWvF/292-add-sidebar-left-and-tailwindcss)

2021-09-04 13:32 UTC, samuveth commented
![](https://github.trello.services/images/mini-trello-icon.png) [Add sidebar left and tailwindcss](https://trello.com/c/s6COWWvF/292-add-sidebar-left-and-tailwindcss)

2021-09-04 16:39 UTC, bonustrack requested changes
Wow great work, you're almost done! I found some issues but small ones, mostly about spacing / alignment here is the list:
- On the plugins page the name of the plugins are not aligned
![image](https://user-images.githubusercontent.com/16245250/132098348-ee4009f2-b427-439b-89a1-4b0f91e04928.png)
- The icon for login is not properly aligned
![image](https://user-images.githubusercontent.com/16245250/132098457-7be91b06-7be3-4247-86b9-317eca4b9037.png)
- Sidebar should be hidden on small screen
- There should be some space between title and preview of a proposal here:
![image](https://user-images.githubusercontent.com/16245250/132101784-4640ac95-fae0-47d6-9858-c794f10d4311.png)
- The strategies icons not aligned here: 
![image](https://user-images.githubusercontent.com/16245250/132101804-7d2e539c-152c-43ce-a2a3-d060afdb222e.png)
- The bg color of the loading placeholder should use the skin var, now it's the same everywhere sometime it doesn't render well see:
![image](https://user-images.githubusercontent.com/16245250/132101826-fb58ab17-5d3f-4d09-96aa-5a95e410c0dd.png)
- Sidebar bg should use this bg-skin-block-bg color:
![image](https://user-images.githubusercontent.com/16245250/132101894-49abb812-c6ac-45c9-b06e-14b1bc2a5e23.png)

2021-09-05 02:08 UTC, samuveth commented on package.json
> +    "autoprefixer": "^10.3.3",
Yeah, I'm keeping them until the end incase I need them for testing.

2021-09-05 02:52 UTC, samuveth commented
Cool, fixed those

> Sidebar bg should use this bg-skin-block-bg color:

It does use that already, no?

2021-09-05 07:39 UTC, bonustrack commented
> It does use that already, no?
Nope it doesn't, i mean about the main sidebar. It should be white here:
![image](https://user-images.githubusercontent.com/16245250/132119310-df479a76-0ec4-4dd1-b26f-c252c5ceceee.png)

2021-09-05 07:45 UTC, bonustrack commented
Others things i forgot:
- Not a fan of this:
![image](https://user-images.githubusercontent.com/16245250/132119370-dc7c8281-6b67-4a88-bd9c-4c03691ad19d.png)
I'd rather keep it the way is it was before, with full rounded pill and without "Open".

- I think for now we should show the space that you follow on the main page too. Main page give extra information (numbers of active proposals). We can remove it later when we change some others behavior.

2021-09-05 08:07 UTC, bonustrack commented
- Background color shouldnt change on mouse over:
![image](https://user-images.githubusercontent.com/16245250/132120056-32c18045-1999-4eae-916c-2586bd235296.png)

2021-09-05 08:12 UTC, metrox-eth commented
<img width="430" alt="Capture d’écran 2021-09-05 à 15 06 56" src="https://user-images.githubusercontent.com/55286013/132120154-cb1859fc-4c02-49df-855a-d2cf818eb732.png">
Howdy ! Noticied that the incremential selector is overlapping the pill on mouse over.

2021-09-05 08:38 UTC, metrox-eth commented
<img width="1241" alt="Capture d’écran 2021-09-05 à 15 30 07" src="https://user-images.githubusercontent.com/55286013/132120747-d306200c-4003-4c24-8ef0-e2812f3b503b.png">
Slightly larger line spacing here

<img width="475" alt="Capture d’écran 2021-09-05 à 15 22 53" src="https://user-images.githubusercontent.com/55286013/132120751-7498b9d9-59d0-4302-bba6-fc0ff4aab631.png">
Log out text color style is missing

2021-09-05 08:39 UTC, samuveth commented
> Sidebar bg should use this bg-skin-block-bg color:

You mean `bg-skin-block-bg` or `bg-skin-header-bg` because where you are pointing the arrow is `bg-skin-header-bg`

2021-09-05 08:41 UTC, samuveth commented
> * I'd rather keep it the way is it was before, with full rounded pill and without "Open".

It doesn't look very good without the border around the space image.

2021-09-05 08:47 UTC, samuveth commented
> * Background color shouldnt change on mouse over:

I added that because currently it's looks very flat, with the join button being very prominent and the user could miss that you can also view a space by clicking on it.

2021-09-05 09:03 UTC, metrox-eth commented
<img width="1420" alt="Capture d’écran 2021-09-05 à 15 45 13" src="https://user-images.githubusercontent.com/55286013/132121406-e83b8cb8-58b1-4605-8259-166f95459037.png">

Slightly different line spacing add over the height of this section.

<img width="1241" alt="Capture d’écran 2021-09-05 à 15 42 45" src="https://user-images.githubusercontent.com/55286013/132121415-100deae1-0a14-41b0-94c4-269752e1a45e.png">

Missing element here

2021-09-05 09:23 UTC, samuveth commented
@metrox-eth thanks a lot for your help!

2021-09-05 11:24 UTC, bonustrack commented
@samuveth i mean skin block bg

2021-09-05 11:33 UTC, metrox-eth commented
<img width="1431" alt="Capture d’écran 2021-09-05 à 18 18 08" src="https://user-images.githubusercontent.com/55286013/132125121-c71e5ee4-d1a3-499d-99c6-e0ca93aa982c.png">

Spacing btw address and pill


<img width="1318" alt="Capture d’écran 2021-09-05 à 18 23 44" src="https://user-images.githubusercontent.com/55286013/132125143-bfd306fa-c8f3-4ce8-8c14-afff686e891e.png">

Upload text background missing


<img width="1318" alt="Capture d’écran 2021-09-05 à 18 26 16" src="https://user-images.githubusercontent.com/55286013/132125166-d7f1e194-2a17-4f1c-92ec-223e382eb44d.png">

Placeholder text color


<img width="1318" alt="Capture d’écran 2021-09-05 à 18 27 39" src="https://user-images.githubusercontent.com/55286013/132125175-4a3cf16f-fa89-432a-a541-6c3b380b8731.png">

Placeholder text color and title bg height

2021-09-05 11:38 UTC, metrox-eth commented
<img width="1318" alt="Capture d’écran 2021-09-05 à 18 37 05" src="https://user-images.githubusercontent.com/55286013/132125341-4e9a5e8d-1271-48b9-a703-96a7d69addd2.png">

Title size

2021-09-06 13:13 UTC, bonustrack commented
- SafeSnap layout is broken test here: https://bafybeigfqj3vc6qpq5gustfudjtal6r4p2dsx6ksc2czw5h3th6cjngmau.on.fleek.co/#/fabien.eth/proposal/QmV2TVKZmgXHuzT36ockuJ3hwCY31weotgirYTsA18SBDB In proposal creation too test here: https://bafybeigfqj3vc6qpq5gustfudjtal6r4p2dsx6ksc2czw5h3th6cjngmau.on.fleek.co/#/fabien.eth/create
- Add background color from the skin on sidebar space icon so i doesnt look like this:
![image](https://user-images.githubusercontent.com/16245250/132222064-08bf7f74-d37b-4a41-bf02-65b24ca46464.png)
- Try reduce slightly the space between space icon in sidebar
- Check if something is wrong with 3box? Can't see my image here: https://bafybeigfqj3vc6qpq5gustfudjtal6r4p2dsx6ksc2czw5h3th6cjngmau.on.fleek.co/#/fabien.eth/proposal/QmUQ3ytu3JQdbVScFVkEsPtPHc6REEKCtYb7wTcaKkukrR

2021-09-06 13:24 UTC, bonustrack commented
Also something wrong with progress bar on block results. We should use the primary color then reduce by 15% opacity for each strategy.

2021-09-07 04:42 UTC, samuveth commented
@bonustrack ready for merge from my side. I will improve the progress bar and tooltip in another PR.

2021-09-07 08:30 UTC, bonustrack commented
Border shouldn't appear on mobile here:
![image](https://user-images.githubusercontent.com/16245250/132312022-1065dbfa-a10c-4a93-9151-a82042f6334f.png)

2021-09-07 08:31 UTC, bonustrack commented
Same for proposal creation, we shouldnt have this right border on mobile
![image](https://user-images.githubusercontent.com/16245250/132312134-8342feb5-32ae-40cf-a723-45fc5a6607c1.png)

2021-09-07 08:34 UTC, bonustrack commented
Also can you reduce the space in green and increase in red? It should look same as on snapshot.org
![image](https://user-images.githubusercontent.com/16245250/132312500-a67436c1-aa8b-4a28-bf1f-d86342f93df6.png)

2021-09-07 08:34 UTC, bonustrack commented
Feel free to merge once you've done these changes

2021-09-07 11:38 UTC, samuveth commented
> Feel free to merge once you've done these changes

@bonustrack Ok please approve

2021-09-07 13:35 UTC, bonustrack approved these changes

2021-09-07 13:38 UTC, merged