Add chart plugin
snapshot-labs/snapshot pull request #949
Opened 2021-10-26 01:07 UTC by Zerquix18

Better late than never! It's been a busy month for me.

This continues #596  
Addresses the feedback [here](https://github.com/snapshot-labs/snapshot/pull/596#issuecomment-932775711).

2021-11-02 21:21 UTC, mktcode requested changes

2021-11-02 21:21 UTC, mktcode commented on src/components/Plugin/Charts/CustomBlock.vue
> +    <div class="py-3 flex flex-row">
```suggestion
    <div class="flex flex-row justify-between -m-4 border-b">
```

2021-11-02 21:21 UTC, mktcode commented on src/components/Plugin/Charts/CustomBlock.vue
> +        class="block px-4 py-2 sidenav-item"
```suggestion
        class="block px-4 py-2 sidenav-item w-[150px]"
```

2021-11-02 21:21 UTC, mktcode commented on src/components/Plugin/Charts/CustomBlock.vue
> +        class="block px-4 py-2 sidenav-item"
```suggestion
        class="block px-4 py-2 sidenav-item w-[150px]"
```

2021-11-02 21:21 UTC, mktcode commented on src/components/Plugin/Charts/CustomBlock.vue
> +    <div v-if="votes.length > 0">
```suggestion
    <div v-if="votes.length > 0" class="mt-6">
```

2021-11-02 21:21 UTC, mktcode commented on src/components/Plugin/Charts/CustomBlock.vue
> +    <div v-if="votes.length === 0">
```suggestion
    <div v-if="votes.length === 0" class="mt-6">
```

2021-11-02 21:31 UTC, mktcode commented
@Zerquix18 @bonustrack  With my suggested changes the tabs look like this:

![image](https://user-images.githubusercontent.com/6792578/139954279-3f9845e4-d5fa-4b4f-b87d-df5143a32d53.png)
![image](https://user-images.githubusercontent.com/6792578/139954331-5141b9bb-a118-49bf-b621-fe82e9dd9f86.png)

2021-11-04 20:41 UTC, bonustrack commented
@mktcode I like that!

2021-11-05 12:47 UTC, mktcode approved these changes

2021-11-08 17:37 UTC, bonustrack approved these changes

2021-11-08 17:38 UTC, merged